# Generated by Django 3.1.5 on 2021-05-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_auto_20210528_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
