# Generated by Django 3.1.5 on 2021-06-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_auto_20210528_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt',
        ),
    ]
