# Generated by Django 3.1.5 on 2021-05-23 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveSmallIntegerField(null=True)),
                ('square_meters', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('owner', models.BooleanField(default=False)),
                ('heating', models.FloatField(null=True)),
                ('elevator', models.FloatField(null=True)),
                ('general_expenses', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('cellphone', models.PositiveIntegerField(null=True)),
                ('role', models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('TENANT', 'Tenant'), ('SITE-ADMIN', 'Site Admin')], max_length=13)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=200, null=True)),
                ('receipt', models.CharField(max_length=200, null=True)),
                ('total', models.FloatField(null=True)),
                ('payment_made', models.BooleanField(default=False)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.apartment')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('document', models.FileField(upload_to='')),
                ('type_expenses', models.CharField(choices=[('HEATING', 'Heating'), ('ELEVATOR', 'Elevator'), ('GENERAL', 'General')], default='GENERAL', max_length=10)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('floors', models.PositiveSmallIntegerField(null=True)),
                ('apartments', models.PositiveSmallIntegerField(null=True)),
                ('reserve', models.FloatField(null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.profile')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.building'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.profile'),
        ),
    ]
