# Generated by Django 3.1.5 on 2021-05-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('TENANT', 'Tenant'), ('SITE_ADMIN', 'Site Admin')], max_length=13),
        ),
    ]
