# Generated by Django 3.1.5 on 2021-05-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20210523_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
