# Generated by Django 3.1.5 on 2021-06-14 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_auto_20210608_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petroleum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(null=True)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('total_oil', models.FloatField(null=True)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.building')),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(null=True)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('consumption', models.PositiveIntegerField(null=True)),
                ('apartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.apartment')),
            ],
        ),
    ]
