# Generated by Django 3.1.5 on 2021-06-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_consumption_petroleum'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='fi',
            field=models.FloatField(null=True),
        ),
    ]
