# Generated by Django 3.1.5 on 2021-06-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_apartment_fi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Petroleum',
        ),
    ]
